name: Generate firmware
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
      - run: bundle install
      - run: bundle exec rake
      - uses: actions/upload-artifact@v4
        with:
            name: firmware
            path: bin/*
