name: Building Firmware Images
run-name: Building Firmeware Images
on: [push]
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v4
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1' 
      - name: Restore Download Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: openwrt-imagebuilder-*.tar.xz
          key: download-cache
      - name: Install Build depdencies
        run: sudo apt-get install -y rake build-essential make gawk rclone 
      - run: rake
        name: Building Firmware
      - uses: actions/upload-artifact@v4
        name: Uploading Firmware Artifacts
        with:
            name: firmware
            path: bin/*-squashfs-combined.img.gz
      - name: Save Download Cache
        id: cache-save
        uses: actions/cache@v4
        with:
          path: openwrt-imagebuilder-*.tar.xz
          key: download-cache
      - name: Deploy to Nextcloud
        run: rclone copy bin/\*-squashfs-combined.img.gz rshare:/${{ vars.GITHUB_JOB }}