name: Building Firmware Images
run-name: Building Firmeware Images
on: [push]
jobs:
  Build:
    runs-on: ubuntu-24.04
    strategy:
  	  matrix:
    	  nodes: ["nodes-apu.yml", "nodes-giot.yml"]
    env:
        RCLONE_CONFIG_RSHARE_VENDOR: nextcloud
        RCLONE_CONFIG_RSHARE_TYPE: webdav
        RCLONE_CONFIG_RSHARE_PASS: ${{ secrets.RCLONE_CONFIG_RSHARE_PASS }}
        RCLONE_CONFIG_RSHARE_URL: ${{ secrets.RCLONE_CONFIG_RSHARE_URL }}
        RCLONE_CONFIG_RSHARE_USER: ${{ secrets.RCLONE_CONFIG_RSHARE_USER }}
        NODES_FILE: $ {{ matrix.nodes }}
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v4
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' 
      - name: Restore Download Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            openwrt-imagebuilder-*
          key: download-cache
      - name: Install Build depdencies
        run: sudo apt-get install -y rake build-essential make gawk rclone 
      - run: rake
        name: Building Firmware
      - uses: actions/upload-artifact@v4
        name: Uploading Firmware Artifacts
        with:
            name: firmware
            path: bin/*-squashfs-combined.img.gz
      - name: Save Download Cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            openwrt-imagebuilder-*
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
      - name: Deploy to Nextcloud
        run: rclone sync bin/ rshare:firmware/