name: Generate firmware
run-name: ${{ github.actor }} building firmeware
on: [push]
jobs:
  Build-images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1' 
      - name: Restore cached Primes
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /var/cache/apt/archives
            openwrt-imagebuilder-*.tar.xz
          key: download-cache
      - run: sudo apt-get install -y rake build-essential make gawk
      - run: rake
      - uses: actions/upload-artifact@v4
        with:
            name: firmware
            path: bin/*-squashfs-combined.img.gz
      - name: Cache downloads
        id: cache-save
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            openwrt-imagebuilder-*.tar.xz
          key: ${{ steps.cache-restore.outputs.download-cache }}